WS2-459 Plugin for lists.
ASUWebPlatforms/webspark-module-webspark_ckeditor_plugins pull request #4
Opened 2021-06-08 09:29 UTC by deptant

This plugin provides contextual menus for Bulleted and Ordered Lists. Right clicking on a list fires a contextual menu which gives options depending on the type of list. Multi level lists do not support some styling options, so a message is displayed explaining this.

This plugin relies on updates to Lists in the theme which have already been deployed to RC2 and a PR is available on the Renovation theme also.

2021-06-09 04:31 UTC, mlsamuelson commented
Looping @imorale2 Into this. Looks like the list variant names are using outdated list terminology... "Smoke mode" and such, instead of the now standardized "gray" names, ala https://unity.web.asu.edu/@asu-design-system/bootstrap4-theme/index.html?path=/story/components-list--unordered-list

@imorale2 I'm guessing you want to align on the updated naming going forward...

2021-06-09 04:32 UTC, mlsamuelson requested changes
See the note about the updated list names.  I'm marking this as changes requested, but please check in with @imorale2 on the path forward.

2021-06-10 12:59 UTC, deptant commented
I have updated the color names and added logic to prevent users applying styles within an already styled multi list.

2021-06-10 14:27 UTC, mlsamuelson approved these changes
Approved. Thank you, @deptant .

@imorale2 On the UDS side, we eventually need to update the class naming regarding the grayscale colors in the markup so it's more standardized, but at least in the frontend, both UDS and WS2 will match the Web Standards naming conventions.

2021-06-10 16:07 UTC, merged